---
abstract: "create a hash where the default value is ain't undef"
author:
  - '<http://purl.org/NET/cpan-uri/person/tobyink>'
  - '<http://purl.org/NET/cpan-uri/person/voj>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.61
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Hash::DefaultValue
name: Hash-DefaultValue
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Tie::Hash: 0
  constant: 0
  perl: 5.6.0
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Hash-DefaultValue
  homepage: https://metacpan.org/release/Hash-DefaultValue
  license: http://dev.perl.org/licenses/
version: 0.004
