---
abstract: "create a hash where the default value ain't undef"
author:
  - 'TOBYINK <tobyink@cpan.org>'
  - 'VOJ <voj@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::More: '0.61'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Moose::Meta::Class::__ANON__::SERIAL::11 version , CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Hash-DefaultValue
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Hash::DefaultValue:
    file: lib/Hash/DefaultValue.pm
    version: '0.007'
  Hash::Missing:
    file: lib/Hash/Missing.pm
    version: '0.007'
requires:
  Carp: '0'
  Tie::Hash: '0'
  constant: '1.06'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Hash-DefaultValue/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Hash-DefaultValue
  homepage: https://metacpan.org/release/Hash-DefaultValue
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-hash-defaultvalue.git
version: '0.007'
